name: community
description: CommUnity â€” The Most Beautiful Event App (Better than Luma)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  connectivity_plus: ^6.0.3 # For checking network status
  google_fonts: ^6.3.3
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.3.2
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  uuid: ^4.4.0
  confetti: ^0.7.0
  android_alarm_manager_plus: ^4.0.3
  hive: ^2.2.3 # stable hive version at time of writing
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  web_socket_channel: ^2.2.0
  socket_io_client: ^2.0.3
  flutter_riverpod: ^2.5.1
  flutter_keyboard_visibility: ^6.0.0
  riverpod_annotation: ^2.3.5
  flutter_typeahead: ^5.0.2
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  url_launcher: ^6.3.2
  web: ^1.1.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  mockito: ^5.4.4
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
